"""add_name_to_budget_items

Revision ID: 3ac0e1c865f3
Revises: 9c9a764dc357
Create Date: 2026-05-26 12:14:31.547999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac0e1c865f3'
down_revision: Union[str, None] = '9c9a764dc357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_items', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_items', 'name')
    # ### end Alembic commands ###
