"""drop_unique_budget_item_category

Revision ID: 43969625ba33
Revises: 3ac0e1c865f3
Create Date: 2026-05-26 16:00:45.264085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43969625ba33'
down_revision: Union[str, None] = '3ac0e1c865f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_budget_items_budget_category'), 'budget_items', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_budget_items_budget_category'), 'budget_items', ['budget_id', 'category_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
