"""add_budget_item_id_to_transactions

Revision ID: c349b5ac2892
Revises: 43969625ba33
Create Date: 2026-05-27 14:17:12.425107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c349b5ac2892'
down_revision: Union[str, None] = '43969625ba33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('budget_item_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'budget_items', ['budget_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'budget_item_id')
    # ### end Alembic commands ###
